### ISSUE TITLE
Supply two random seeds via config

### ISSUE THREAD

**Issue by schmittkl** [schmittkl/FARM#3] opened 2021-09-15 14:10 UTC
Currently, FARM takes one random seed for model training, which is then used in two different places.

We want to change the code such that we can supply two different random seeds. Also, it would be great if we could supply them via code and config files.

**Comment by schmittkl** [comment] 2021-09-16 11:32
The "seed" supplied via config is currently used for more than two parameters:
```python
def set_all_seeds(seed, deterministic_cudnn=False):
    """
    Setting multiple seeds to make runs reproducible.
    Important: Enabling `deterministic_cudnn` gives you full reproducibility with CUDA,
    but might slow down your training (see https://pytorch.org/docs/stable/notes/randomness.html#cudnn) !
    :param seed:number to use as seed
    :type seed: int
    :param deterministic_torch: Enable for full reproducibility when using CUDA. Caution: might slow down training.
    :type deterministic_cudnn: bool
    :return: None
    """
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    torch.cuda.manual_seed_all(seed)
    if deterministic_cudnn:
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False
```
Do I adjust both random seed and create a third one for the other values? Or does it make sense to use different seeds for all of these values?

**Comment by rjschmitt** [comment] 2021-09-20 11:00
duplicate of https://github.com/schmittkl/FARM/issues/5

**Closed as completed by rjschmitt** 2021-09-20 11:00 UTC
Labels: enhancement
